<a href="https://colab.research.google.com/github/jegatheshwaran/Numpy_Task_2/blob/main/Copy_of_Numpy_tasks_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__

'1.21.6'

In [ ]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
np.size(a)

10

In [ ]:
a.itemsize

8

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(a)

class:  ndarray
shape:  (10,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x27a02b0
byteorder:  little
byteswap:  False
type: float64


In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
b = np.zeros(10)
b[4] = 1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
a = np.arange(10,50)
b = a[::-1]
b

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
a = np.nonzero([1,2,0,0,4,0])
a

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
import numpy as np
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
a = np.random.uniform((3,3,3))
a

array([1.3305476 , 2.08780391, 2.3243704 ])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
z = np.random.random((10,10))
z

array([[0.82447819, 0.98309851, 0.28242753, 0.11838874, 0.97397199,
        0.69217796, 0.02724174, 0.916609  , 0.7060075 , 0.34614089],
       [0.52185458, 0.06018941, 0.01393171, 0.19592805, 0.47010036,
        0.11954789, 0.50646993, 0.77916777, 0.88103663, 0.22208034],
       [0.96917566, 0.00976195, 0.46578723, 0.01107146, 0.11966105,
        0.43205202, 0.94437984, 0.54938373, 0.58083101, 0.72780816],
       [0.47017455, 0.85164666, 0.79061699, 0.96484606, 0.83674444,
        0.89328942, 0.69967401, 0.0118515 , 0.32255759, 0.46997146],
       [0.69254964, 0.56417279, 0.88426894, 0.42221956, 0.58053845,
        0.44697813, 0.79864319, 0.36395264, 0.08315568, 0.11437773],
       [0.40500799, 0.23738944, 0.27887015, 0.75926216, 0.24806773,
        0.44062146, 0.27605728, 0.24122375, 0.90169211, 0.27533199],
       [0.22800121, 0.98152196, 0.00714818, 0.67992617, 0.97360599,
        0.073449  , 0.98023628, 0.57618369, 0.41536298, 0.22817192],
       [0.23719128, 0.06057734, 0.113012 

In [ ]:
z.min(),z.max()

(0.006067832867807987, 0.9830985136092224)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
j = np.random.random(30)
z = j.mean()
z

0.48113246872446674

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
np.pad

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
z = np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2 ,1::2]=1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
a = np.array([[0,1],[1,0]])
a

array([[0, 1],
       [1, 0]])

In [ ]:
b = np.tile(a,(8,8))
b

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
a = np.random.random((5,5))
a

array([[0.31923288, 0.95512546, 0.5592555 , 0.66961813, 0.04876478],
       [0.7162959 , 0.52427287, 0.1727289 , 0.05281058, 0.90042754],
       [0.62994501, 0.34896592, 0.69073617, 0.74195478, 0.01427646],
       [0.01879616, 0.81118953, 0.83638478, 0.61076033, 0.03091975],
       [0.23365267, 0.92066132, 0.65329532, 0.4358365 , 0.79073095]])

In [ ]:
amin , amax = a.min() , a.max()
a = (a - amin) / (amax - amin)
a

array([[0.10071667, 0.47567285, 0.285341  , 0.31509538, 0.19550352],
       [0.79707811, 0.74026531, 0.68414979, 0.        , 0.92649131],
       [0.12994174, 0.2180752 , 0.11122231, 0.93294412, 0.70011522],
       [1.        , 0.92355787, 0.49493471, 0.04546966, 0.66733384],
       [0.07084378, 0.67820575, 0.39941229, 0.17970045, 0.73337883]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
colour = np.dtype([('r',np.ubyte, 1),
                   ('g',np.ubyte, 1),
                   ('b',np.ubyte, 1),
                   ('a',np.ubyte, 1),
                   ])
colour

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
z = np.dot( np.ones((5,3)), np.ones((3,2)) )
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [ ]:
y = ( np.ones((5,3)) @ np.ones((3,2)) )
y

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
n = np.arange(-1,10)
n[ (3<n) & (n<=8) ] *= -1
n

array([-1,  0,  1,  2,  3, -4, -5, -6, -7, -8,  9])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

NameError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
a = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
n = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(n)),n))

[-4.  4.  7. -7. -7.  4. -7.  2.  9.  3.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[0 1 3 4 5 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [61]:
a = np.seterr(all="ignore")
print(a)
b = np.ones(1)/0
print(b)
c = np.seterr(**a)
print(c)
with np.errstate(all='ignore'):
  np.arange(3)/0

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}
[inf]
{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
z = np.arange('2016-07' , '2017-08' , dtype='datetime64[D]')
z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31', '2016-08-01',
       '2016-08-02', '2016-08-03', '2016-08-04', '2016-08-05',
       '2016-08-06', '2016-08-07', '2016-08-08', '2016-08-09',
       '2016-08-10', '2016-08-11', '2016-08-12', '2016-08-13',
       '2016-08-14', '2016-08-15', '2016-08-16', '2016-08-17',
       '2016-08-18', '2016-08-19', '2016-08-20', '2016-08-21',
       '2016-08-22', '2016-08-23', '2016-08-24', '2016-08-25',
       '2016-08-26', '2016-08-27', '2016-08-28', '2016-08-29',
       '2016-08-30', '2016-08-31', '2016-09-01', '2016-

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [64]:
a = np.arange(5)*1
print(a)
b = np.arange(5)*2
print(b)
np.add(a,b,out=b)

[0 1 2 3 4]
[0 2 4 6 8]


array([ 0,  3,  6,  9, 12])

In [67]:
a = np.arange(5)*1
print(a)
b = np.arange(5)*2
print(b)
np.negative(a,out=a)

[0 1 2 3 4]
[0 2 4 6 8]


array([ 0, -1, -2, -3, -4])

In [68]:
a = np.arange(5)*1
print(a)
b = np.arange(5)*2
print(b)
np.multiply(a,b,out=b)

[0 1 2 3 4]
[0 2 4 6 8]


array([ 0,  2,  8, 18, 32])

In [71]:
a = np.ones(5)*1
print(a)
np.divide(a,2,out=a)

[1. 1. 1. 1. 1.]


array([0.5, 0.5, 0.5, 0.5, 0.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
y = np.arange(0,10,10)

print( y - y%1)
print( np.floor(y) )
print( np.ceil(y)-1 )
print(z.astype(int))
print( np.trunc(y) )

[0]
[0.]
[-1.]
[16983 16984 16985 16986 16987 16988 16989 16990 16991 16992 16993 16994
 16995 16996 16997 16998 16999 17000 17001 17002 17003 17004 17005 17006
 17007 17008 17009 17010 17011 17012 17013 17014 17015 17016 17017 17018
 17019 17020 17021 17022 17023 17024 17025 17026 17027 17028 17029 17030
 17031 17032 17033 17034 17035 17036 17037 17038 17039 17040 17041 17042
 17043 17044 17045 17046 17047 17048 17049 17050 17051 17052 17053 17054
 17055 17056 17057 17058 17059 17060 17061 17062 17063 17064 17065 17066
 17067 17068 17069 17070 17071 17072 17073 17074 17075 17076 17077 17078
 17079 17080 17081 17082 17083 17084 17085 17086 17087 17088 17089 17090
 17091 17092 17093 17094 17095 17096 17097 17098 17099 17100 17101 17102
 17103 17104 17105 17106 17107 17108 17109 17110 17111 17112 17113 17114
 17115 17116 17117 17118 17119 17120 17121 17122 17123 17124 17125 17126
 17127 17128 17129 17130 17131 17132 17133 17134 17135 17136 17137 17138
 17139 17140 17141 17142 17143 17144

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
a = np.zeros((5,5))
a = a+np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [78]:
iterable = (a*a for a in range(10))
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
z = np.linspace(0,1,11, endpoint=False)[:-1]
z

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
np.random.random(10)
z.sort()
z

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
a = np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)

In [ ]:
same = np.allclose(a,b)
same

False

In [ ]:
same = np.array_equal(a,b)
same

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
z = np.ones(10)
z.flags.writeable = False
z[0]=1

ValueError: ignored

In [ ]:
import numpy as np
a = np.arange(100)
a.flags.writeable = False
a[0]=1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [80]:
a = np.random.random((10,2))
b,c = a[:,0], a[:,1]
d = np.sqrt(b**2+c**2)
print(d)
e = np.arctan2(b,a)
print(e)

[0.90208919 0.71670724 0.87248457 0.80730984 0.94809308 0.48706547
 0.79563038 0.63337263 0.97980369 0.4039423 ]


ValueError: ignored

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
a = np.random.random(10)
a

array([0.18702752, 0.44711395, 0.37908914, 0.21294751, 0.3494998 ,
       0.21789308, 0.54454394, 0.61184557, 0.38065938, 0.205426  ])

In [ ]:
a[a.argmax()]=12
a

array([ 0.18702752,  0.44711395,  0.37908914,  0.21294751,  0.3494998 ,
        0.21789308,  0.54454394, 12.        ,  0.38065938,  0.205426  ])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
a = np.arange(20)
b = np.random.random(10)
c,d = np.meshgrid(a,b)
print(c,d)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]] [[0.49657373 0.49657373 0.49657373 0.49657373 0.49657373 0.49657373
  0.49657373 0.49657373 0.49657373 0.49657373 0.49657373 0.49657373
  0.49657373 0.49657373 0.49657373 0.49657373 0.49657373 0.49657373
  0.49657373 0.49657373]
 [0.87126584 0.87126584 0.87126584 0.87126584 0.87126584 0.87126584
  0.87126584 0.87126584 0.87126584 0.87126584 0.87126584 0.87126584
  0.

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
a = np.arange(10)
print(a)
b = np.random.randint(10)
print(b)
print(np.subtract.outer(a,b))

[0 1 2 3 4 5 6 7 8 9]
8
[-8 -7 -6 -5 -4 -3 -2 -1  0  1]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
j = np.zeros(10)
g = np.iinfo(np.int16)
g

iinfo(min=-32768, max=32767, dtype=int16)

In [ ]:
j = np.zeros(10)
g = np.iinfo(np.int32)
g

iinfo(min=-2147483648, max=2147483647, dtype=int32)

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
#a = np.arange(10)
np.set_printoptions(threshold=5)
a = np.arange(10)
print(a)

[0 1 2 ... 7 8 9]


In [ ]:
b = np.array([9,8,7,6,5,4,3,2,1])
np.set_printoptions(precision=7)
b

array([9, 8, 7, ..., 3, 2, 1])

In [ ]:
b = np.array([9.876995564077644])
np.set_printoptions(precision=7)
b

array([9.8769956])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
a = np.arange(-1,18)
np.argmin(a, axis=0)

0

In [ ]:
a = np.arange(20).reshape(5,4)
np.argmin(a, axis=0)

array([0, 0, 0, 0])

In [ ]:
a = np.random.random(100)
np.argmin(a, axis=0)

43

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [81]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
y = np.random.randint(50)
np.atleast_2d(y)

array([[14]])

In [ ]:
y = np.random.random(50)
np.atleast_2d(y)

array([[0.2626388, 0.1798622, 0.61818  , ..., 0.1557429, 0.9734311,
        0.9358651]])

In [ ]:
y = np.array([1,2,3,4])
np.atleast_2d(y)

array([[1, 2, 3, 4]])

In [ ]:
z = np.arange(10)
np.atleast_2d(z)

array([[0, 1, 2, ..., 7, 8, 9]])

In [ ]:
a = np.random.random((10,2))
x = np.atleast_2d(a[:,0])
z = np.sqrt((x-x.T)**2)
z

array([[0.       , 0.3476171, 0.1917957, ..., 0.0307207, 0.0774847,
        0.2888303],
       [0.3476171, 0.       , 0.1558215, ..., 0.3783378, 0.2701324,
        0.0587868],
       [0.1917957, 0.1558215, 0.       , ..., 0.2225163, 0.1143109,
        0.0970347],
       ...,
       [0.0307207, 0.3783378, 0.2225163, ..., 0.       , 0.1082054,
        0.319551 ],
       [0.0774847, 0.2701324, 0.1143109, ..., 0.1082054, 0.       ,
        0.2113456],
       [0.2888303, 0.0587868, 0.0970347, ..., 0.319551 , 0.2113456,
        0.       ]])

In [ ]:
a = np.random.random((10,2))
x = np.atleast_2d(a[:,1])
z = np.sqrt((x-x.T)**2)
z

array([[0.       , 0.6959098, 0.1095218, ..., 0.008456 , 0.3704795,
        0.154151 ],
       [0.6959098, 0.       , 0.586388 , ..., 0.7043658, 0.3254303,
        0.8500608],
       [0.1095218, 0.586388 , 0.       , ..., 0.1179778, 0.2609577,
        0.2636728],
       ...,
       [0.008456 , 0.7043658, 0.1179778, ..., 0.       , 0.3789355,
        0.145695 ],
       [0.3704795, 0.3254303, 0.2609577, ..., 0.3789355, 0.       ,
        0.5246305],
       [0.154151 , 0.8500608, 0.2636728, ..., 0.145695 , 0.5246305,
        0.       ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
a = np.array([7,5,4,3],dtype=float)
print(a)
b = a.astype(np.int32,copy=False)
print(b)

[7. 5. 4. 3.]
[7 5 4 3]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [88]:
from io import StringIO
a = StringIO('''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11''')
Z = np.genfromtxt(a, delimiter=",",dtype=np.int)
Z

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
a = np.random.random(10).reshape(5,2)
for i,j in np.ndenumerate(a):
  print(i,j)


(0, 0) 0.5491145929905571
(0, 1) 0.4116844739915586
(1, 0) 0.6505913093933205
(1, 1) 0.9202707258389764
(2, 0) 0.17864849713096698
(2, 1) 0.8292206156319911
(3, 0) 0.9024339487413149
(3, 1) 0.45213125282043465
(4, 0) 0.07145618312884894
(4, 1) 0.25464121871509193


In [ ]:
a=(1,2,3,4,5)
for i in np.ndindex(a):
  print(i)

(0, 0, 0, 0, 0)
(0, 0, 0, 0, 1)
(0, 0, 0, 0, 2)
(0, 0, 0, 0, 3)
(0, 0, 0, 0, 4)
(0, 0, 0, 1, 0)
(0, 0, 0, 1, 1)
(0, 0, 0, 1, 2)
(0, 0, 0, 1, 3)
(0, 0, 0, 1, 4)
(0, 0, 0, 2, 0)
(0, 0, 0, 2, 1)
(0, 0, 0, 2, 2)
(0, 0, 0, 2, 3)
(0, 0, 0, 2, 4)
(0, 0, 0, 3, 0)
(0, 0, 0, 3, 1)
(0, 0, 0, 3, 2)
(0, 0, 0, 3, 3)
(0, 0, 0, 3, 4)
(0, 0, 1, 0, 0)
(0, 0, 1, 0, 1)
(0, 0, 1, 0, 2)
(0, 0, 1, 0, 3)
(0, 0, 1, 0, 4)
(0, 0, 1, 1, 0)
(0, 0, 1, 1, 1)
(0, 0, 1, 1, 2)
(0, 0, 1, 1, 3)
(0, 0, 1, 1, 4)
(0, 0, 1, 2, 0)
(0, 0, 1, 2, 1)
(0, 0, 1, 2, 2)
(0, 0, 1, 2, 3)
(0, 0, 1, 2, 4)
(0, 0, 1, 3, 0)
(0, 0, 1, 3, 1)
(0, 0, 1, 3, 2)
(0, 0, 1, 3, 3)
(0, 0, 1, 3, 4)
(0, 0, 2, 0, 0)
(0, 0, 2, 0, 1)
(0, 0, 2, 0, 2)
(0, 0, 2, 0, 3)
(0, 0, 2, 0, 4)
(0, 0, 2, 1, 0)
(0, 0, 2, 1, 1)
(0, 0, 2, 1, 2)
(0, 0, 2, 1, 3)
(0, 0, 2, 1, 4)
(0, 0, 2, 2, 0)
(0, 0, 2, 2, 1)
(0, 0, 2, 2, 2)
(0, 0, 2, 2, 3)
(0, 0, 2, 2, 4)
(0, 0, 2, 3, 0)
(0, 0, 2, 3, 1)
(0, 0, 2, 3, 2)
(0, 0, 2, 3, 3)
(0, 0, 2, 3, 4)
(0, 1, 0, 0, 0)
(0, 1, 0, 0, 1)
(0, 1, 0

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [91]:
X, Y = np.meshgrid(np.linspace(-1,1,3), np.linspace(-1,1,3))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.60653066 0.36787944]
 [0.60653066 1.         0.60653066]
 [0.36787944 0.60653066 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
import numpy as np
n = 10
p = 3
a = np.zeros((n,n))
a.put(np.random.choice(range(n*n),p,replace=True),1)
print(a)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
z = np.random.rand(5,10)
y = z - z.mean(axis=1,keepdims=True)
print(y)

[[-0.215669   -0.10081224 -0.02797409  0.31044142  0.25765108 -0.06200673
   0.08165838  0.01580052 -0.12895548 -0.13013386]
 [ 0.41740195  0.15440658  0.23257128 -0.19807698 -0.35351393 -0.00860649
  -0.15210346  0.09183021 -0.05916257 -0.1247466 ]
 [ 0.12141291  0.00214572  0.13482942 -0.18661632  0.11599945 -0.1576469
  -0.22208296  0.15659615 -0.09939051  0.13475304]
 [-0.37023798 -0.12236235 -0.35380737  0.31652314 -0.05815835  0.25745794
   0.36305466  0.42102304 -0.20910486 -0.24438788]
 [-0.20283976 -0.51152416  0.19991138 -0.3714824   0.35881815  0.10969094
  -0.08707822  0.35026051  0.28832616 -0.1340826 ]]


In [ ]:
z = np.random.rand(10,3)
y = z - z.mean(axis=1,keepdims=True)
print(y)

[[ 0.04900428  0.24907623 -0.29808051]
 [ 0.37534577  0.08067482 -0.45602059]
 [-0.49756844  0.23443891  0.26312953]
 [-0.12696627  0.00590227  0.121064  ]
 [ 0.23118756 -0.10596144 -0.12522612]
 [ 0.18379345 -0.21157932  0.02778587]
 [ 0.12114971  0.01529528 -0.13644498]
 [-0.04697208  0.30082531 -0.25385323]
 [-0.04853818 -0.40715512  0.45569329]
 [-0.29816429 -0.02870903  0.32687332]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
n = np.random.random((5,5))
print(n)
print(n[n[:,1].argsort()])

[[0.68847152 0.03500945 0.57903119 0.81502884 0.24141539]
 [0.7147368  0.81952224 0.15675641 0.75272486 0.27856949]
 [0.12247607 0.17972685 0.55022024 0.00882936 0.62503184]
 [0.00452666 0.59957606 0.07354103 0.56588206 0.15980548]
 [0.11175048 0.25995336 0.92679906 0.45329154 0.54214359]]
[[0.68847152 0.03500945 0.57903119 0.81502884 0.24141539]
 [0.12247607 0.17972685 0.55022024 0.00882936 0.62503184]
 [0.11175048 0.25995336 0.92679906 0.45329154 0.54214359]
 [0.00452666 0.59957606 0.07354103 0.56588206 0.15980548]
 [0.7147368  0.81952224 0.15675641 0.75272486 0.27856949]]


In [ ]:
n = np.random.randint(0,5,(3,3))
print(n)
print(n[n[:,1].argsort()])

[[4 3 0]
 [2 0 1]
 [0 0 4]]
[[2 0 1]
 [0 0 4]
 [4 3 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
a = np.random.random(9).reshape(3,3)
print(a)
print((~a.any(axis=0)).any())

[[0.90850422 0.7254572  0.10386163]
 [0.9999095  0.7520093  0.78863512]
 [0.79705297 0.20099662 0.35784887]]
False


In [ ]:
b = np.random.randint(0,2,(5,5))
print(b)
print((~b.any(axis=1)).any())

[[1 0 0 0 1]
 [0 1 0 0 1]
 [1 0 1 1 0]
 [0 1 0 1 1]
 [0 0 0 0 1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
import numpy as np
a = np.random.random(1)
print(a)
A = 1
n = a.flat[np.abs(a-A).argmin()]
n

[0.7388618]


0.7388617975892544

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
import numpy as np
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
  z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [95]:
class guvi:
  def __init__(self,name,mobile):
    self.name = name
    self.mobile = mobile
list=[]
list.append(guvi('jegathesh',9894789760))
list.append(guvi('waran',98895509))
list.append(guvi('ssss',97857877))

for i in list:
  print(i.name,i.mobile,sep=' ')

jegathesh 9894789760
waran 98895509
ssss 97857877


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [98]:
a = np.ones(5)
b = np.random.randint(0,len(a),10)
c = np.bincount(b, minlength = len(a))
c

array([3, 2, 2, 1, 2])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
a = [1,3,5,7,9]
b = [2,4,6,8,10]
c = np.bincount(a,b)
c

array([ 0.,  2.,  0.,  4.,  0.,  6.,  0.,  8.,  0., 10.])

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


In [ ]:
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)
I

array([[[0, 3, 2],
        [3, 2, 1],
        [1, 0, 1],
        ...,
        [3, 1, 1],
        [2, 1, 1],
        [1, 2, 3]],

       [[0, 3, 2],
        [1, 0, 3],
        [1, 2, 3],
        ...,
        [0, 3, 1],
        [0, 1, 3],
        [1, 3, 1]],

       [[0, 0, 1],
        [2, 2, 0],
        [3, 3, 3],
        ...,
        [3, 3, 3],
        [1, 2, 0],
        [0, 0, 2]],

       ...,

       [[2, 2, 2],
        [1, 3, 2],
        [1, 3, 1],
        ...,
        [0, 0, 0],
        [0, 2, 0],
        [0, 0, 0]],

       [[1, 1, 2],
        [3, 3, 2],
        [1, 3, 3],
        ...,
        [1, 0, 2],
        [3, 0, 1],
        [0, 0, 3]],

       [[1, 3, 1],
        [0, 1, 3],
        [2, 2, 3],
        ...,
        [1, 2, 1],
        [2, 1, 0],
        [0, 1, 0]]], dtype=uint8)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
a = np.random.randint(0,10,(3,4,3,4))
print(a)
sum = a.sum(axis=(2,1))
sum

[[[[1 2 7 9]
   [2 2 9 2]
   [6 5 4 6]]

  [[4 9 5 7]
   [3 4 7 4]
   [3 8 3 9]]

  [[7 4 0 6]
   [0 4 3 0]
   [6 6 3 8]]

  [[2 0 3 7]
   [6 8 7 3]
   [6 2 3 2]]]


 [[[1 1 5 4]
   [5 5 9 9]
   [7 3 7 9]]

  [[1 0 6 2]
   [2 5 2 3]
   [7 8 7 7]]

  [[0 9 3 5]
   [4 0 1 3]
   [0 7 7 1]]

  [[7 3 4 2]
   [3 3 8 1]
   [2 5 9 7]]]


 [[[0 9 1 2]
   [0 9 0 3]
   [7 8 8 0]]

  [[1 2 1 9]
   [9 3 9 5]
   [5 3 0 0]]

  [[5 7 8 9]
   [7 8 3 3]
   [9 4 4 1]]

  [[9 6 4 0]
   [4 0 6 8]
   [9 9 7 0]]]]


array([[46, 54, 54, 63],
       [39, 49, 68, 53],
       [65, 68, 51, 40]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
a = np.random.uniform(0,1,100)
print(a)

array([0.91540524, 0.27574016, 0.45658245, 0.83437095, 0.51978057,
       0.68393329, 0.68990082, 0.377589  , 0.29347344, 0.46379624,
       0.10788326, 0.14326686, 0.41327298, 0.05857518, 0.87956204,
       0.55701558, 0.44995178, 0.37042861, 0.27796048, 0.3828624 ,
       0.57600266, 0.98103386, 0.4312456 , 0.19354982, 0.41506728,
       0.27322734, 0.88089676, 0.26099048, 0.28923181, 0.06532699,
       0.26630538, 0.38214147, 0.24660874, 0.06747827, 0.04846111,
       0.08537445, 0.60250564, 0.75991773, 0.89765448, 0.57780026,
       0.6706723 , 0.81041263, 0.9733192 , 0.77838327, 0.66425604,
       0.10039186, 0.73462371, 0.49383895, 0.65554768, 0.28121862,
       0.72469217, 0.97393999, 0.13497869, 0.05578402, 0.19265217,
       0.16700707, 0.67680142, 0.31628865, 0.20303214, 0.7653345 ,
       0.55923288, 0.37797544, 0.24889392, 0.04631893, 0.96155341,
       0.95304939, 0.52353898, 0.75068613, 0.52787012, 0.15880638,
       0.6683747 , 0.69002814, 0.24135298, 0.05298407, 0.90141

In [ ]:
b = np.random.randint(0,10,100)
b

array([5, 9, 0, 2, 8, 7, 9, 9, 6, 5, 7, 3, 7, 8, 9, 9, 7, 9, 0, 8, 6, 5,
       1, 4, 2, 2, 9, 0, 3, 0, 2, 8, 9, 6, 0, 9, 0, 0, 3, 5, 5, 0, 8, 8,
       0, 4, 5, 5, 5, 4, 3, 9, 0, 2, 7, 6, 9, 5, 2, 3, 6, 7, 5, 4, 8, 7,
       9, 8, 9, 7, 9, 1, 2, 6, 0, 6, 0, 9, 9, 0, 9, 4, 4, 2, 0, 9, 4, 9,
       1, 2, 1, 0, 1, 9, 4, 3, 3, 3, 9, 4])

In [ ]:
c = np.bincount(b,weights=a)
c

array([ 6.79750995,  2.94610765,  3.31576105,  4.82071367,  2.80685555,
        6.05790081,  1.71741005,  3.33752469,  4.80730164, 11.42998943])

In [ ]:
d = np.bincount(b)
d

array([15,  5,  9,  8,  9, 10,  7,  8,  8, 21])

In [ ]:
e = c/d
e

array([0.45316733, 0.58922153, 0.36841789, 0.60258921, 0.31187284,
       0.60579008, 0.24534429, 0.41719059, 0.60091271, 0.54428521])

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
a = np.random.uniform(1,2,(5,5))
b = np.random.uniform(2,3,(5,5))
np.diag(np.dot(a,b))

array([18.47234887, 16.09715788, 21.05772281, 17.48906915, 20.43226475])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
a = np.array([1,2,3,4,5])
b = 3
c = np.ones(len(a)+(len(a)-1)*(b))
c[::b+1] = b
c

array([3., 1., 1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3.])

In [ ]:
a = np.array([1,2,3,4,5])
b = 3
c = np.ones(len(a)+(len(a)-1)*(b))
c[::b+1] = a
c

array([1., 1., 1., 1., 2., 1., 1., 1., 3., 1., 1., 1., 4., 1., 1., 1., 5.])

In [ ]:
b = 3
c = np.zeros(len(a)+(len(a)-1)*(b))
c[::b+1] = a
c

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
a = np.ones((5,5,3))
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
b = 2*np.ones((5,5))
b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [ ]:
c = a*b[:,:,None]
c

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
a = np.random.uniform(0,10,10).reshape(5,2)
print(a)
a[[0,1]] = a[[1,0]]
a

[[9.3980604  0.13574766]
 [6.01070467 8.88377666]
 [5.47284965 3.44725566]
 [4.91348901 0.86346425]
 [2.68416121 9.07843137]]


array([[6.01070467, 8.88377666],
       [9.3980604 , 0.13574766],
       [5.47284965, 3.44725566],
       [4.91348901, 0.86346425],
       [2.68416121, 9.07843137]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
a = np.random.randint(1,100,(10,3))
a

array([[45, 99, 44],
       [50, 24, 54],
       [20, 38, 17],
       [33,  5, 97],
       [72,  4,  6],
       [50, 66, 20],
       [16, 22, 93],
       [13, 71, 86],
       [37, 92, 36],
       [22, 69, 45]])

In [ ]:
b = np.roll(a.repeat(2,axis=1),-1,axis=1)
b

array([[45, 99, 99, 44, 44, 45],
       [50, 24, 24, 54, 54, 50],
       [20, 38, 38, 17, 17, 20],
       [33,  5,  5, 97, 97, 33],
       [72,  4,  4,  6,  6, 72],
       [50, 66, 66, 20, 20, 50],
       [16, 22, 22, 93, 93, 16],
       [13, 71, 71, 86, 86, 13],
       [37, 92, 92, 36, 36, 37],
       [22, 69, 69, 45, 45, 22]])

In [ ]:
c = np.roll(a.repeat(2,axis=0),-1,axis=1)
c

array([[99, 44, 45],
       [99, 44, 45],
       [24, 54, 50],
       [24, 54, 50],
       [38, 17, 20],
       [38, 17, 20],
       [ 5, 97, 33],
       [ 5, 97, 33],
       [ 4,  6, 72],
       [ 4,  6, 72],
       [66, 20, 50],
       [66, 20, 50],
       [22, 93, 16],
       [22, 93, 16],
       [71, 86, 13],
       [71, 86, 13],
       [92, 36, 37],
       [92, 36, 37],
       [69, 45, 22],
       [69, 45, 22]])

In [ ]:
b = b.reshape(len(b)*3,2)
b

array([[45, 99],
       [99, 44],
       [44, 45],
       [50, 24],
       [24, 54],
       [54, 50],
       [20, 38],
       [38, 17],
       [17, 20],
       [33,  5],
       [ 5, 97],
       [97, 33],
       [72,  4],
       [ 4,  6],
       [ 6, 72],
       [50, 66],
       [66, 20],
       [20, 50],
       [16, 22],
       [22, 93],
       [93, 16],
       [13, 71],
       [71, 86],
       [86, 13],
       [37, 92],
       [92, 36],
       [36, 37],
       [22, 69],
       [69, 45],
       [45, 22]])

In [ ]:
b = np.sort(b,axis=1)
b

array([[ 4,  6],
       [ 4, 20],
       [ 5, 22],
       [ 5, 33],
       [ 6, 37],
       [13, 38],
       [13, 38],
       [16, 45],
       [16, 45],
       [17, 50],
       [17, 50],
       [20, 54],
       [20, 54],
       [20, 66],
       [22, 66],
       [22, 69],
       [22, 69],
       [24, 71],
       [24, 72],
       [33, 72],
       [36, 86],
       [36, 86],
       [37, 92],
       [44, 92],
       [44, 93],
       [45, 93],
       [45, 97],
       [50, 97],
       [50, 99],
       [71, 99]])

In [ ]:
c = b.view(dtype=[('p0',b.dtype),('p1',b.dtype)])
c

array([[( 4,  6)],
       [( 4, 20)],
       [( 5, 22)],
       [( 5, 33)],
       [( 6, 37)],
       [(13, 38)],
       [(13, 38)],
       [(16, 45)],
       [(16, 45)],
       [(17, 50)],
       [(17, 50)],
       [(20, 54)],
       [(20, 54)],
       [(20, 66)],
       [(22, 66)],
       [(22, 69)],
       [(22, 69)],
       [(24, 71)],
       [(24, 72)],
       [(33, 72)],
       [(36, 86)],
       [(36, 86)],
       [(37, 92)],
       [(44, 92)],
       [(44, 93)],
       [(45, 93)],
       [(45, 97)],
       [(50, 97)],
       [(50, 99)],
       [(71, 99)]], dtype=[('p0', '<i8'), ('p1', '<i8')])

In [ ]:
c = np.unique(c)
c

array([( 4,  6), ( 4, 20), ( 5, 22), ( 5, 33), ( 6, 37), (13, 38),
       (16, 45), (17, 50), (20, 54), (20, 66), (22, 66), (22, 69),
       (24, 71), (24, 72), (33, 72), (36, 86), (37, 92), (44, 92),
       (44, 93), (45, 93), (45, 97), (50, 97), (50, 99), (71, 99)],
      dtype=[('p0', '<i8'), ('p1', '<i8')])

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
c = np.bincount([1,1,2,3,4,5,5])
a = np.repeat(np.arange(len(c)),c)
a

array([1, 1, 2, 3, 4, 5, 5])

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [2]:
import numpy as np
def moving_average(a, n) :
    test = np.cumsum(a, dtype=float)
    test[n:] = test[n:] - test[:-n]
    return test[n - 1:] / n
moving_average(np.arange(20),5)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [6]:
a = np.arange(30)
n = 3
c = np.cumsum(a,dtype=float)
c[n:] = c[n:] - c[:-n]
print(c[n-1:]/n)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28.]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
a = np.random.randint(1,5,10)
np.logical_not(a, out=a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
a = np.random.randint(1,4,10)
print(a)
np.negative(a, out=a)

[1 3 1 1 3 2 1 2 3 2]


array([-1, -3, -1, -1, -3, -2, -1, -2, -3, -2])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [18]:
p0 = np.random.uniform(-10,10,(10,2))
print(p0)

[[ 1.7496077  -0.91438646]
 [-4.33336795  1.3664441 ]
 [ 0.10437438  8.24554001]
 [-9.88629987  6.30755717]
 [ 7.84876234 -4.96990057]
 [-7.65305583 -6.80526453]
 [ 7.29023059  1.86103347]
 [ 4.69700315  9.91198438]
 [-2.54006419  6.74118369]
 [-0.40555178  2.79138654]]


In [19]:
p1 = np.random.uniform(-10,10,(10,2))
print(p1)

[[-7.65522379  4.95672428]
 [ 8.65389336 -5.64022618]
 [ 9.64071132  7.20593995]
 [-1.68931422 -9.3907961 ]
 [-1.12333309 -4.71122741]
 [ 8.03950004 -9.51112608]
 [ 3.26404964  0.49366548]
 [-2.8305347   2.71157046]
 [-5.15968471 -0.84251565]
 [ 9.20062342  8.17432162]]


In [9]:
p = np.random.uniform(-10,10,(1,2))
print(p)

[[-2.48280525 -3.44893634]]


In [10]:
t = p1 - p0
t

array([[ -4.80817024,   5.09935083],
       [ 16.64257967,  10.30422072],
       [ -0.10938909,   1.89807898],
       [ -0.9248701 ,  -3.02550814],
       [ 16.37286635,  -7.94933041],
       [ 18.68359962,  11.94839023],
       [  5.40416406,   1.10957266],
       [-12.40037473,  11.14831033],
       [ -9.16634463,  -7.52981843],
       [ -6.37282312, -11.7911343 ]])

In [11]:
l = (t**2).sum(axis=1)
l

array([ 49.12187994, 383.15242292,   3.6146698 ,  10.0090842 ,
       331.2626063 , 491.8409239 ,  30.43614071, 278.05411659,
       140.72003952, 179.64372243])

In [12]:
u = -((p0[:,0]-p[...,0])*t[:,0]+(p0[:,1]-p[...,1])*t[:,1])/l
u

array([0.94884562, 0.19544535, 0.26586182, 0.17473883, 0.49668695,
       0.33857657, 0.22092071, 0.49539669, 0.36799925, 0.84507749])

In [13]:
u = u.reshape(len(u),1)
u

array([[0.94884562],
       [0.19544535],
       [0.26586182],
       [0.17473883],
       [0.49668695],
       [0.33857657],
       [0.22092071],
       [0.49539669],
       [0.36799925],
       [0.84507749]])

In [14]:
d = p0 + u*t - p
d

array([[ 7.26141191,  6.84677438],
       [-2.82016942,  4.55491933],
       [-2.97892172, -0.17167965],
       [ 1.63573609, -0.50002953],
       [ 3.39451193,  6.99151845],
       [-1.04663294,  1.63661132],
       [-0.00857364,  0.04175785],
       [ 3.53040088,  3.92689946],
       [ 0.29587088, -0.36017528],
       [-1.58152539,  0.85477625]])

In [15]:
np.sqrt((d**2).sum(axis=1))

array([9.98030172, 5.35729836, 2.9838647 , 1.71045669, 7.7720037 ,
       1.94266238, 0.04262892, 5.28055582, 0.46611781, 1.79773885])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [21]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

NameError: ignored

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [22]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print (rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [24]:
Z = np.random.randint(0,10,50)
print( np.bincount(Z).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [25]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 0 3]
   [3 0 0]
   [2 4 0]]

  [[0 3 2]
   [0 0 0]
   [4 0 2]]

  [[3 2 3]
   [0 0 0]
   [0 2 4]]

  [[2 3 0]
   [0 0 0]
   [2 4 4]]

  [[3 0 2]
   [0 0 0]
   [4 4 0]]

  [[0 2 0]
   [0 0 0]
   [4 0 3]]

  [[2 0 3]
   [0 0 2]
   [0 3 3]]

  [[0 3 3]
   [0 2 0]
   [3 3 3]]]


 [[[3 0 0]
   [2 4 0]
   [2 3 1]]

  [[0 0 0]
   [4 0 2]
   [3 1 3]]

  [[0 0 0]
   [0 2 4]
   [1 3 1]]

  [[0 0 0]
   [2 4 4]
   [3 1 0]]

  [[0 0 0]
   [4 4 0]
   [1 0 1]]

  [[0 0 0]
   [4 0 3]
   [0 1 3]]

  [[0 0 2]
   [0 3 3]
   [1 3 3]]

  [[0 2 0]
   [3 3 3]
   [3 3 3]]]


 [[[2 4 0]
   [2 3 1]
   [0 0 4]]

  [[4 0 2]
   [3 1 3]
   [0 4 3]]

  [[0 2 4]
   [1 3 1]
   [4 3 0]]

  [[2 4 4]
   [3 1 0]
   [3 0 2]]

  [[4 4 0]
   [1 0 1]
   [0 2 2]]

  [[4 0 3]
   [0 1 3]
   [2 2 4]]

  [[0 3 3]
   [1 3 3]
   [2 4 2]]

  [[3 3 3]
   [3 3 3]
   [4 2 2]]]


 [[[2 3 1]
   [0 0 4]
   [3 2 2]]

  [[3 1 3]
   [0 4 3]
   [2 2 2]]

  [[1 3 1]
   [4 3 0]
   [2 2 0]]

  [[3 1 0]
   [3 0 2]
   [2 0 4]]

  [[1 0 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [28]:
p, n = 10, 10
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [29]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [31]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [43]:
a = np.array([('hi',1,2),
              ('hello',3,4)])
b = np.core.records.fromarrays(a.T,names='col1,col2,col3',formats='S8,f8,i8')
b

rec.array([(b'hi', 1., 2), (b'hello', 3., 4)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [45]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.59 s ± 10.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
74.7 ms ± 297 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
65.9 ms ± 688 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [46]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[1 2 3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [47]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[1 3 2]
 [1 1 1]
 [3 1 2]
 [3 4 0]
 [4 3 2]
 [3 3 1]
 [2 2 0]
 [2 2 0]
 [0 4 0]
 [4 4 1]]
[[1 3 2]
 [3 1 2]
 [3 4 0]
 [4 3 2]
 [3 3 1]
 [2 2 0]
 [2 2 0]
 [0 4 0]
 [4 4 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [50]:
a = np.array([0, 1, 2, 3], dtype=np.uint8)
print(np.unpackbits(a[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [52]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print(np.einsum('i,i', A, B))
print(np.einsum('i,j->ij', A, B))
print(np.einsum('i->', A))
print(np.einsum('i,i->i', A, B))

2.3469204664348435
[[2.50371019e-01 3.63817480e-01 5.30495268e-01 7.39228575e-01
  3.31695893e-01 4.80877822e-01 4.79213485e-01 6.53335637e-03
  9.26979215e-01 9.61539022e-01]
 [2.19737972e-01 3.19304188e-01 4.65588847e-01 6.48783507e-01
  2.91112698e-01 4.22042126e-01 4.20581421e-01 5.73399622e-03
  8.13562741e-01 8.43894134e-01]
 [2.17633027e-01 3.16245466e-01 4.61128814e-01 6.42568590e-01
  2.88324031e-01 4.17999242e-01 4.16552530e-01 5.67906833e-03
  8.05769349e-01 8.35810188e-01]
 [1.43845321e-01 2.09023561e-01 3.04784723e-01 4.24707986e-01
  1.90568790e-01 2.76278080e-01 2.75321871e-01 3.75360033e-03
  5.32576106e-01 5.52431705e-01]
 [6.35231768e-02 9.23063787e-02 1.34595229e-01 1.87554245e-01
  8.41566127e-02 1.22006481e-01 1.21584211e-01 1.65761817e-03
  2.35189619e-01 2.43958001e-01]
 [1.07495704e-01 1.56203447e-01 2.27765828e-01 3.17384563e-01
  1.42412184e-01 2.06462794e-01 2.05748218e-01 2.80506805e-03
  3.97994481e-01 4.12832583e-01]
 [1.13235069e-01 1.64543394e-01 2.39926

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [55]:
a = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
b = 4
c = np.logical_and.reduce(np.mod(a, 1) == 0, axis=-1)
c &= (a.sum(axis=-1) == n)
print(a[c])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [54]:
a = np.random.randn(100) 
b = 1000 
idx = np.random.randint(0, a.size, (b, a.size))
means = a[idx].mean(axis=1)
c = np.percentile(means, [2.5, 97.5])
print(c)

[-0.21656864  0.22062595]
